---
- hosts: qa
  vars:
    system: "Windows"
    color: "Red"
  tasks:
    # - debug: var=hostvars
    - debug: var=ansible_system
    - debug: var=color
      when: system == 'Linux'
    - debug: var=item
      with_items:
        - item1
        - item2
